# Generated by Django 2.2.1 on 2019-06-02 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['position'], 'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterModelOptions(
            name='storyboard',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='storyboard',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='api.Story'),
        ),
    ]
