# Generated by Django 2.2.1 on 2019-06-08 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavigationDestination',
            new_name='NavigationTab',
        ),
    ]
